### ISSUE TITLE
[Bug] Removing last pinned user glitches plugin out

### ISSUE THREAD

**Issue by BeSlightly** [Syncxv/betterPinDMs#2]
When unpinning the last user inside of a category the plugin starts completly glitching out (see attached webm)
This is usually fixed with a reload, but I also had this persist through a reload, can't replicate it right now tho.

[Untitled.webm](https://github.com/Syncxv/betterPinDMs/assets/80231852/9d08c136-2d57-49d3-84b5-25658aabcbcf)

**Comment by Syncxv** [comment]
nice catch. it should be fixed here [c0542de](https://github.com/Syncxv/betterPinDMs/commit/c0542de4e6f5c2bc2f19035b32fe060716bd30d6)

update and see if that works.

**Comment by BeSlightly** [comment]
Yeah, seems to have fixed it, can't reproduce it anymore.
Closing the issue, thanks a lot!
